version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
      - ./frontend/.env
    networks:
      - fullstack-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
      - ./backend/.env
    networks:
      - fullstack-network
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.docs.rule=Host(`${DOMAIN}`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.redoc.rule=Host(`${DOMAIN}`) && PathPrefix(`/redoc`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - ./backend/.env
    networks:
      - fullstack-network
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer
    restart: always
    networks:
      - fullstack-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.${DOMAIN}`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "--entrypoints.websecure.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$1"
      - "--entrypoints.websecure.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - fullstack-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.${DOMAIN}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

volumes:
  postgres_data:

networks:
  fullstack-network:

